## Question 1

In [3]:
import numpy as np

In [5]:
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

## Question 2

In [23]:
print("Enter list A of Element 5")
A = []
for i in range(5):
    print("Enter Element",i+1,)
    A.append(int(input()))
print("Enter list B of Element 5")    
B = []
for i in range(5):
    print("Enter Element",i+1,)
    B.append(int(input()))
Arr1 = np.array(A)
Arr2 = np.array(B)
np.concatenate((Arr1,Arr2))

Enter list A of Element 5
Enter Element 1
1
Enter Element 2
2
Enter Element 3
3
Enter Element 4
4
Enter Element 5
5
Enter list B of Element 5
Enter Element 1
1
Enter Element 2
2
Enter Element 3
3
Enter Element 4
4
Enter Element 5
5


array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

## Question 3 

In [29]:
Arr1.shape

(5,)

In [30]:
Arr1.size

5

In [27]:
Arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

## Question 4

In [31]:
Arr3 = np.array([1,3,4,5,6,6])

In [46]:
Arr3

array([1, 3, 4, 5, 6, 6])

In [43]:
Arr4 = Arr3[np.newaxis,:]

In [44]:
Arr4.shape

(1, 6)

In [45]:
Arr4

array([[1, 3, 4, 5, 6, 6]])

## Question 5

In [61]:
A = np.arange(16)

In [62]:
A.shape

(16,)

In [63]:
A.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
A = A.reshape(4,4)

In [65]:
B = np.arange(16)

In [66]:
B.shape

(16,)

In [67]:
B.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
B = B.reshape(4,4)

In [74]:
np.hstack((A,B))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15]])

In [75]:
np.vstack((A,B))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Question 6

In [76]:
A1 = np.array([1,4,3,2,4,1,2,2,3,4,5,4,123,4,4234,53,11,3,3,2,4,5,])

In [80]:
A2 = np.unique(A1)

In [81]:
A2

array([   1,    2,    3,    4,    5,   11,   53,  123, 4234])

In [84]:
A2.shape[0]

9

In [85]:
print("Unique Elements =",A2.shape[0] )

Unique Elements = 9
